name: DEMO WORKflow
on:
  push:
    branches:  [master]
    paths:
      - .github/workflows/demo.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      # step 1: Checkout Role
      - name:  Checkout code
        uses: actions/checkout@v3

      # Step 2: Print environmet variable
      - name: Print environmet variable
        run: echo "Deploying version ${{ vars.APP_VERSION }}"

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn clean install

      # Step 4: Use secret for API call
      - name: Use secret safely
        env: 
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "Connecting with API key (masked): $API_KEY"
          curl -H "Authorization: Bearer $API_KEY" https://api.example.com/status/

      # Step 5: Coditional Apply
      - name: Deploy to Prod
        if: github.ref == "refs/heads/master"
        run: echo "Deploying to production environment..."
        
    
    
