name: DEMO WORKflow
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Print environment variable
        run: echo "Deploying version ${{ vars.APP_VERSION }}"
      - name: Use secret safely
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo "Connecting with API key $API_KEY"
